### PR TITLE
Support maps for args

### PR DESCRIPTION
**Pull request by philipcristiano**

### CODE REVIEW

**Comment by seriyps** [comment]
I would say, it needs to be backwards-compatible

**Comment by philipcristiano** [comment]
That's a good point. I meant to make this against my own fork :/ 

At the moment pgapp points to the devel branch for epgsql. I ran into the examples for this repo breaking when I went to use this. 

I'll see if I can get some time to make this backwards compatible and update the examples as well.

**Comment by philipcristiano** [comment]
@seriyps updated, please let me know what you think!

**Comment by seriyps** [comment]
It's fine. Another approach would be to just convert proplist to map and use map after that, like it was done in epgsql:

https://github.com/epgsql/epgsql/blob/5304480f24789d370fb637dcc649d12688f525ff/src/epgsql.erl#L155

https://github.com/epgsql/epgsql/blob/5304480f24789d370fb637dcc649d12688f525ff/src/epgsql.erl#L455-L459

But I'm ok with your solution as well. Maybe @davidw have smth to add?

**Pull request closed without merging**
