### PR TITLE
Configuration and pools

### PR DESCRIPTION
**Pull request by fooflare**
Hi, I have made some changes to make easier to init the application and added to the API the possibility of using multiple pools.

Just as summary:
 - Added a configuration file sample and its management in pgapp_sup.
 - Added get dependencies and compile as default action in Makefile.
 - Added run option in Makefile to start the application.
 - Added instructions of the changes to README file.
 - Removed `poolboy` from applications flag in pgapp.app.src file to avoid an error when starting the application.

I am not sure if you want to apply these changes, but I did it for me, so I make the PR if you want to consider it :)

And thank you for this repo, it helped me a lot to understand how poolboy and epgsql work.

### CODE REVIEW

**Comment by davidw** [comment]
@fooflare cool!  Good work.  I have just a few thoughts:

* Requiring a pool name kind of takes away from the simplicity of the default interface.  It'd be really nice if that were optional.
* Are you sure about removing poolboy from pgapp.app.src ?

**Comment by fooflare** [comment]
I was thinking last night about it, because it has no sense to give a name when you just want to use a simple pool, so I agree with you :) I will add it.

About removing the poolboy from applications, I realized that if I started the poolboy application (explicitly, from Makefile) before pgapp, it worked perfectly. But just removing it from the src.app, and starting pgapp, it worked in the same way just creating the pool workers in the pgapp_sup, at least in the tests I made.

**Comment by fooflare** [comment]
@davidw I added the simple pool API again.

If you have any question or suggestion, I am at your disposal.

**Comment by davidw** [comment]
Cool, thanks!

**Pull request merged**
