### PR TITLE
Hex package and rebar3

### PR DESCRIPTION
**Pull request by Licenser**
Hi I've published pgapp to hex, this PR includes the changes that were required. If you are interested in taking the package over I'll gladly give it back :).

PS: I've added myself as a secondary maintainer there for the moment so people don't bother you with hex package related, feel free to remove that.

### CODE REVIEW

**Comment by davidw** [comment]
Please make changes against the `devel` branch, as per the README.  Then we can release that.  I'm more than happy to have you be the go-to person for the Hex package, although please do make sure there's a pointer to the epgsql github page and mailing list.

Thank you!

**Comment by Licenser** [comment]
there is no `devel` branch to make a PR against ;) but I'll put the links in the package description!

**Comment by davidw** [comment]
Oops, my apologies!  I missed the 'pgapp' thing.

**Comment by Licenser** [comment]
no worries :) thanks for the swift reply!

**Comment by davidw** [comment]
I see that the rebar.config changes too... is there any way that backwards compatibility can be maintained?  I haven't followed rebar3 much, unfortunately.

**Pull request closed without merging**
